# -*- coding: utf-8 -*-
"""
Created on Wed Oct  9 16:10:04 2019

@author: Francois
"""

from secrets import randbelow as rb
from flatten import flatten

def randInsert(lst, item, insertFreq=2):
    """Insert item to random index in lst
    ...
    
    Description
    -----------
    Inserts 'item' (can be any variable a list can contain)
    in 'lst' (a list) at a random index generated by 
    secret.ranbelow() module imported as rb.
        -cryptographically secure random values 
    
    The advantage of using this method over using built-in
    list .insert() method is that randInsert() returns a
    new list containing all items (from 'lst'+'item'),
    while .insert() returns None. This makes it harder to
    keep track of all images at any moment during experiments.
    ...
    
    Parameters:
        lst: list object
        item: any type variable
    ---------------------------
    Variables:
        sliceIndex: type = int
            A randomly generated integer where lst is sliced
        lstTop: type = list
            Upper slice of lst (from lst[0] to lst[sliceIndex])
            'item' will be appended to lstTop after lstTop[sliceIndex].
            'lstBottom' will be appended to lstTop after lstTop[item].
        lstBottom: type = list
            Lower slice of lst (from lst[sliceIndex] to lst[len(lst)-1])
            Will be appended to 'lstTop' after lstTop[item].
            
    ----------------------------------
    Return:
        newlst: unidimensional list
            Calls flatten(lst) to vectorize 'lstTop'
            see <help(flatten)> for more details
    """
    sliceIndexes = [rb(len(lst)) for sInd in range(len(lst)//2)]
    for sInd in sliceIndexes:
#    sliceIndex = rb(len(lst))
        lstTop, lstBottom = lst[:sInd], lst[sInd:]
        lstTop.append(item)
        lstTop.append(lstBottom)
        newlst = flatten(lstTop)
    return newlst
#    return lstTop

lst1 = ['a','b','v','t','y','w']
lst2 = ['e','g','r','i','o','q']
gs = 'graysquare'
newlist = randInsert(lst1,gs,2)

Python
# Insert all the elements in list2 to list1 between 3 to 4 th element
for elem in reversed(list2) :
list1.insert(3, elem)
1
2
3
# Insert all the elements in list2 to list1 between 3 to 4 th element
for elem in lst2 :
    lst1.insert(rb(len(lst1)), elem)